# Generated by Django 2.2 on 2020-11-14 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20201107_1026'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basketapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamBasket',
            new_name='TrainerBasket',
        ),
        migrations.AlterField(
            model_name='trainerbasket',
            name='Team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Trainer'),
        ),
    ]
