# Generated by Django 2.2 on 2020-11-14 11:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0006_auto_20201107_1026'),
        ('basketapp', '0002_auto_20201114_1605'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrainerBasket',
            new_name='Basket',
        ),
    ]
