# Generated by Django 2.2 on 2020-11-14 11:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20201107_1026'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basketapp', '0003_auto_20201114_1632'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Basket',
            new_name='TrainerBasket',
        ),
    ]
