# Generated by Django 2.2 on 2020-11-14 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0004_auto_20201114_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainerbasket',
            old_name='Team',
            new_name='trainer',
        ),
    ]
