# Generated by Django 2.2 on 2020-10-30 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_match_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='line_up',
        ),
        migrations.DeleteModel(
            name='LineUp',
        ),
    ]
