# Generated by Django 2.2 on 2020-10-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20201019_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='command',
            old_name='name',
            new_name='command',
        ),
        migrations.AddField(
            model_name='composition',
            name='command',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
