# Generated by Django 2.2 on 2020-10-30 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20201030_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='team_guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_2', to='mainapp.Team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_1', to='mainapp.Team'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Имя'),
        ),
    ]
