# Generated by Django 2.2 on 2020-10-31 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20201030_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='tool',
        ),
        migrations.AddField(
            model_name='match',
            name='rebounds',
            field=models.IntegerField(default=0, verbose_name='Подборы'),
        ),
        migrations.AlterField(
            model_name='match',
            name='block_shot',
            field=models.IntegerField(default=0, verbose_name='Блокшоты'),
        ),
        migrations.AlterField(
            model_name='match',
            name='broadcast',
            field=models.IntegerField(default=0, verbose_name='Передачи'),
        ),
        migrations.AlterField(
            model_name='match',
            name='interceptions',
            field=models.IntegerField(default=0, verbose_name='Перехваты'),
        ),
        migrations.AlterField(
            model_name='match',
            name='result_match',
            field=models.IntegerField(default=0, verbose_name='Результат матча'),
        ),
        migrations.AlterField(
            model_name='match',
            name='win_guest',
            field=models.BooleanField(default=False, verbose_name='Победа гостей'),
        ),
        migrations.AlterField(
            model_name='match',
            name='win_owner',
            field=models.BooleanField(default=True, verbose_name='Победа хозяев'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='player',
            name='number',
            field=models.IntegerField(default=0, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(max_length=128, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='player',
            name='surname',
            field=models.CharField(max_length=128, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='team',
            name='defeat',
            field=models.IntegerField(default=0, verbose_name='Поражения'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name_team',
            field=models.CharField(max_length=128, verbose_name='Команда'),
        ),
        migrations.AlterField(
            model_name='team',
            name='win',
            field=models.IntegerField(default=0, verbose_name='Победы'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='surname',
            field=models.CharField(max_length=128, verbose_name='Фамилия'),
        ),
    ]
