# Generated by Django 2.2 on 2020-10-19 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_lastmatches_result'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LastMatches',
            new_name='Match',
        ),
    ]
