# Generated by Django 2.2 on 2020-10-21 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_lineup_match'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineup',
            old_name='team',
            new_name='trainer',
        ),
        migrations.RemoveField(
            model_name='lineup',
            name='patronymic',
        ),
    ]
