# Generated by Django 2.2 on 2020-10-21 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20201022_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='command',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.LineUp'),
        ),
    ]
