# Generated by Django 2.2 on 2020-10-21 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20201022_0219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='command',
        ),
    ]
