# Generated by Django 2.2 on 2020-10-21 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_remove_match_command'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='command',
            new_name='team',
        ),
        migrations.AddField(
            model_name='match',
            name='command',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Team'),
            preserve_default=False,
        ),
    ]
