# Generated by Django 2.2 on 2020-10-21 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_auto_20201022_0235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='rival',
            new_name='guests',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='command',
            new_name='owner',
        ),
    ]
