# Generated by Django 2.2 on 2020-10-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_auto_20201022_0248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='guests',
            new_name='guest',
        ),
        migrations.AddField(
            model_name='match',
            name='win_guest',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='match',
            name='win_owner',
            field=models.BooleanField(default=True),
        ),
    ]
