# Generated by Django 2.2 on 2020-10-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_auto_20201022_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='win_guest',
            field=models.BooleanField(default=''),
        ),
        migrations.AlterField(
            model_name='match',
            name='win_owner',
            field=models.BooleanField(default=''),
        ),
    ]
