# Generated by Django 2.2 on 2020-10-21 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_auto_20201022_0258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineup',
            options={'verbose_name': 'Состав команды', 'verbose_name_plural': 'Состав команд'},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name': 'Матчи', 'verbose_name_plural': 'Матч'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Команды', 'verbose_name_plural': 'Команда'},
        ),
        migrations.AlterModelOptions(
            name='trainer',
            options={'verbose_name': 'Тренеры', 'verbose_name_plural': 'Тренер'},
        ),
    ]
